### ISSUE TITLE
Broadcast example/README - Switching channel

### ISSUE THREAD

**Issue by ksachdeva** [espressif/esp-csi#16]
Hi,

In your README, the section on Broadcast mode states:

>How ​​to implement: The packet sending device continuously switches channels to send out packets. ESP32 A, B, and C all obtain the CSI information carried in the broadcast packet of the packet sending device. This method has the highest detection accuracy and reliability.

When you are saying switches channel, does it mean switching wifi channel (e.g 1, 6, 11, etc )?

I would have thought simply broadcasting a packet on a given channel should have been okay.

Really curious to understand and have the clarification.

Many thanks

Regards
Kapil

**Comment by zhanzhaocheng** [comment]
Since the packet sending device does not know the channel of ESP32 A, B, C or the different channels of ESP32 A, B, C,
In order to allow A, B, and C to obtain CSI information, the packet sending device needs to send packets in a full channel.

If you already know the channels A, B, and C are on, you don’t need to switch channels.

**Comment by zhanzhaocheng** [comment]
Hello, @ksachdeva 

Closing this issue, feel free to reopen with more updates. Thanks.
