### ISSUE TITLE
Some questions about esp device selection and ESP-IDF version (AEGHB-661)

### ISSUE THREAD

**Issue by lemon-xhm** [espressif/esp-csi#176]
Hello, I have some questions to ask.
1. In connect_rainmaker, device includes ESP32-s3-saola-1, but I found esp32-s2-saola in the official website.
2. Why is console_test always problematic when I use esp-idf 5.2.1 or 5.1.4? It worked when I switched to 5.0.4.

**Comment by MacChu0315-Espressif** [comment]
Regarding the first issue, thank you for pointing that out. The ESP32-S3-Saola-1 is currently discontinued, and we will correct this text error promptly.

As for the second issue, it is due to our repository not being timely updated for certain versions of the IDF. The currently recommended IDF versions are v5.1, v5.0, and v4.4. We will progressively adapt our repository to support these versions in the future.
