### ISSUE TITLE
phase waveform instability

### ISSUE THREAD

**Issue by zhy102** [espressif/esp-csi#44]
Hi, I managed to get the CSI matrix of 256 bytes and then I plotted the amplitude and phase of these 128 subcarriers.
 However, the amplitude waveform is working well, but the phase waveform feels strange: even the phase waveform of the CSI acquired by the unmanned environment has a large variation in amplitude. 
Here is my matlab code to extract the phase information: `phase=unwrap(angle(CSI_complex)); `
 Can you tell me the reason for the phase instability?

**Comment by gxhen** [comment]
signal phase is prone to be affected by phase noise and the wireless channel. It is reasonable to have unstable phases in the collected CSI.

**Comment by zhy102** [comment]
The CSI amplitude signal from the same sample is very good. Is it because the CSI phase of esp32 device contains a lot of random noise like the CSI phase extracted from Intel 5300 network card, so the phase information cannot be used directly? You can get rid of that noise by linear transformation and so on. Right?



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 22, 2022 23:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [espressif/esp-csi] phase waveform instability (Issue #44)




 
signal phase is prone to be affected by phase noise and the wireless channel. It is reasonable to have unstable phases in the collected CSI.

**Comment by zhanzhaocheng** [comment]
Hello, @zhy102 

Closing this issue, feel free to reopen with more updates. Thanks.

**Comment by ThETyMaNp** [comment]
Hello,

I've encountered a similar issue: I anticipated stable CSI amplitude in a static environment for activity detection. However, I've noticed significant fluctuations, including:

A noticeable mutation in the ESP32's received CSI amplitude, which doesn't follow a Gaussian distribution, as seen in Figures 1 and 2.
<img width="420" alt="fig1" src="https://github.com/espressif/esp-csi/assets/138379342/299d0046-47e1-4f46-9d95-6b51dbade2fb">
<img width="398" alt="fig2" src="https://github.com/espressif/esp-csi/assets/138379342/0b0d666b-11b1-47c5-ac4a-1103b07dfc20">
Variations in the signal's overall amplitude over time, even without people present, as shown in Figure 3.
<img width="397" alt="fig3" src="https://github.com/espressif/esp-csi/assets/138379342/2fc1c896-a4eb-40c0-81f5-bd0837242dd1">

I'm uncertain if this is due to AGC effects or underestimating environmental changes.

Your assistance is greatly appreciated.
Thank you.

**Comment by MacChu0315-Espressif** [comment]
1. Due to the characteristics of electromagnetic waves, the perception range may be larger than you anticipated, and a shielding box would be a more ideal testing environment.
2. Regarding your doubts about AGC, #185 might be helpful to you.
