### ISSUE TITLE
No waveform in the subcarrier amplitude and Cannot collect CSI data (AEGHB-18)

### ISSUE THREAD

**Issue by R88624332** [espressif/esp-csi#84]
I used two esp32s as a transmitter and receiver respectively and connected them successfully. But there is no waveform in the subcarrier amplitude window, as shown below. (please ignore the contents in the ssid and password, I didn't use them)
![image](https://user-images.githubusercontent.com/85300814/202474929-92600012-75c9-4c1c-8f96-4cecda7cf3d3.png)
And in the action collection window, there is NO csv file under the path of _esp-csi/examples/console_test/tools/data_ after I press the start button.

What should I do? Is there something wrong with the configuration? Please help!

**Comment by Troy0630** [comment]
data和model都没有数据是为什么？

**Comment by zhanzhaocheng** [comment]
@R88624332   You enter the following command data in custom and there should be output
`radar --csi_output_type LLFT --csi_output_format base64`

This is because the device does not output csi data by default, and only when the python script is started, an instruction is issued to let the device open csi data to print

**Comment by zhanzhaocheng** [comment]
> data和model都没有数据是为什么？

Are you using ESP32-S3, is there any log output without python tool

**Comment by Troy0630** [comment]
使用的是ESP32可以吗

**Comment by zhanzhaocheng** [comment]
@Troy0630 
ESP32 is working fine

**Comment by zhanzhaocheng** [comment]
Hello, @R88624332 

Closing this issue, feel free to reopen with more updates. Thanks.
